FROM alpine:3.14

WORKDIR /app

EXPOSE 5000

RUN echo "flask morse app" \
&& echo "YO MON! this is the URL to be used ----->>> http://localhost:5000/morse/type_here_your_translation_candidate" \
&& apk add py3-pip \
&& pip install flask

ENV LC_ALL=C.UTF-8

ENV LANG=C.UTF-8

ADD ./app .

RUN ["chmod", "+x", "/app/flask_morse_app_01.py"]

ENTRYPOINT [ "python3", "/app/flask_morse_app_01.py" ]
